### ISSUE TITLE
Padání na některých vstupech

### ISSUE THREAD

**Issue by tuetschek** [b0r3k/dialogue-planner#6]
Nevím, čím to, ale při testování mi to na tomhle spadlo:
```
[I 210618 12:00:18 rule:46] State: {'goal': 'ask_day', 'goal_': 'ask_day', 'date': '2021-06-30'}
[2021-06-18 12:00:18,622] ERROR in app: Exception on /request [POST]                                                                                                                                                                        Traceback (most recent call last):
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/venv_borek/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/venv_borek/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/venv_borek/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/venv_borek/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/webserver/server.py", line 85, in process_request
    response, _ = handler.get_response(dial, rqst["user"])
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/dialmonkey/conversation_handler.py", line 81, in get_response
    dial = component(dial, self.logger)
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/dialmonkey/policy/planner.py", line 98, in __call__
    start = datetime.fromisoformat(event["start"]["dateTime"])
KeyError: 'dateTime'
127.0.0.1 - - [18/Jun/2021 12:00:18] "POST /request HTTP/1.1" 500 -
```
A taky:
```
kdy mám v plánu EDU-AI?
[I 210618 12:02:02 planner:44] NLU: task(goal=ask_event)&inform(name=edu)
[I 210618 12:02:02 rule:46] State: {'goal': 'ask_event', 'goal_': 'ask_event', 'name': 'edu'}
[2021-06-18 12:02:02,757] ERROR in app: Exception on /request [POST]
Traceback (most recent call last):
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/venv_borek/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/venv_borek/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/venv_borek/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/venv_borek/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/webserver/server.py", line 85, in process_request
    response, _ = handler.get_response(dial, rqst["user"])
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/dialmonkey/conversation_handler.py", line 81, in get_response
    dial = component(dial, self.logger)
  File "/mnt/c/Users/Ondra/Documents/supervision/borek/dialogue-planner/dialmonkey/policy/planner.py", line 139, in __call__
    dial.action.append(DAI(intent="inform", slot="place", value=event["location"]))
KeyError: 'location'
```
Vypadá to, že je to related, ale nevím 😳

**Comment by b0r3k** [comment]
Jasně, já tam předpokládám, že všechny eventy vypadají nějak, ale on event v kalendáři ve skutečnosti nemusí mít skoro žádné informace u sebe, takže to pak padá, když se je to snaží vytáhnout. Opraveno.
